config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'places#index'
  resources :places, only: [:index, :show, :new, :create] do
    resources :entries, only: [:new, :create], shallow: false
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/entry.rb
class Entry < ApplicationRecord
  # talks to the "entries" table

  # each entry belongs to a place
  belongs_to :place
end

app/models/place.rb
class Place < ApplicationRecord
  # talks to the "places" table

  # a place can have many entries
  has_many :entries, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  def new
    @place = Place.find(params[:place_id])
    @entry = @place.entries.new
  end

  def create
    @place = Place.find(params[:place_id])
    @entry = @place.entries.new(entry_params)
    if @entry.save
      redirect_to place_path(@place), notice: "Entry added successfully!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  private
    def entry_params
      params.require(:entry).permit(:title, :description, :occurred_on)
    end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  def index
    @places = Place.all.order(created_at: :desc)
  end

  def show
    @place = Place.find(params[:id])
    @entries = @place.entries.order(date: :desc)
    @new_entry = @place.entries.new 
  end

  def new
    @place = Place.new 
  end

  def create
    @place = Place.new(place_params)
    if @place.save
      redirect_to places_path, notice: "Place added successfully!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  private
    def place_params
      params.require(:place).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/entries/_form.html.erb
<%= form_with(model: [place, entry], local: true) do |form| %>
  <% if entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(entry.errors.count, "error") %> prohibited this entry from being saved:</h2>
      <ul>
        <% entry.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :occurred_on, "Date" %><br>
    <%= form.date_field :occurred_on %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/entries/new.html.erb
<h1>New Entry for <%= @place.name %></h1>

<%= render "form", entry: @entry, place: @place %>

<%= link_to 'Back', place_path(@place) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StarterApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/places/index.html.erb
<h1>Places I've Been</h1>

<ul class="places">
  <% @places.each do |place| %>
    <li>
      <%= link_to place.name, place_path(place) %>
    </li>
  <% end %>
</ul>

<p><%= link_to "New Place", new_place_path %></p>

app/views/places/new.html.erb
<h1>New Place</h1>

<%= form_with model: @place, local: true do |form| %>
  <% if @place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@place.errors.count, "error") %> prohibited this place from being saved:</h2>
      <ul>
        <% @place.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit "Create Place" %>
  </div>
<% end %>

<%= link_to 'Back', places_path %>

app/views/places/show.html.erb
<h1><%= @place.name %></h1>

<ul>
  <% @entries.each do |entry| %>
    <li>
      <h3><%= entry.title %></h3>
      <small><%= entry.occurred_on.strftime("%m/%d/%Y") %></small>
      <p><%= simple_format(entry.description) %></p>
    </li>
  <% end %>
</ul>

<p><%= link_to "New Post", new_place_entry_path(@place) %></p>